Fix including Android.mk error
Fixes the following build error:
error: hwcomposer.sdm710 (SHARED_LIBRARIES android-arm64) \
missing libqservice (SHARED_LIBRARIES android-arm64)
error: hwcomposer.sdm710 (SHARED_LIBRARIES android-arm) \
missing libqservice (SHARED_LIBRARIES android-arm)

Bug: 111163725
Change-Id: Idda5dfd51e5a43a7370825bd895d0ed4c31831cc